### PR TITLE
allow for multi files

### PR DESCRIPTION
**Pull request by Platane**
Hi :wave:  Thanks for this project, I find it pretty useful :)

I made some changes to allow to drop multiple files ( gltf file + textures and binaries as separated files ), or a zip file.

demo

Is it something you would consider useful ?

## TODO

- [ ] lazy load JSzip
- [ ] test codeSandbox integration
- [ ] polyfill Object.formEntries for ie support (?)

### CODE REVIEW

**Comment by hsavit1** [comment]
confirmed that this works for me

**Comment by drcmda** [comment]
@Platane didn't catch the notification but looks very useful

**Comment by Platane** [comment]
> @Platane didn't catch the notification but looks very useful

Cool, I can resolve the conflict and clean it up next week. I will update you :+1:

**Comment by SaraVieira** [comment]
It has been 3 years but today I woke up and choose chaos

Thank you so much!

**Comment by Platane** [comment]
Chaos it is! 
thanks !

**Pull request merged**
